spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

plappUrl: http://localhost:3333/plapp/customerdetails/getAllCustomers
pl.rules.loans.eligibility.url: http://i-techno-guru:8082/pl-rules
